export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";
export const SORT_PRODUCTS = "SORT_PRODUCTS";

export const GET_SELECT_PRODUCT_DATA = "GET_SELECT_PRODUCT_DATA";
export const GET_SELECT_PRODUCT_REQ = "GET_SELECT_PRODUCT_REQ";
export const GET_SELECT_SUCCESS = "GET_SELECT_SUCCESS";
export const GET_SELECT_FAILURE = "GET_SELECT_FAILURE";
